version: "3.7"
services:
  example-app:
    build:
      context: ./example-app
      dockerfile: Dockerfile-app
    expose:
      - "8080"
      - "40000"
    ports:
      - "40000:40000"
      - "8080:8080"
    security_opt:
      - "apparmor:unconfined"
    cap_add:
      - "SYS_PTRACE"